name: Package and Release

on:
  push:
    tags:
      - '**'
  
jobs:
  release:
    runs-on: ubuntu-latest
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get git history for changelogs

      - name: Package and release
        uses: BigWigsMods/packager@v2